name: '💬 Teams Notification'
description: 'Trigger a Microsoft Teams Notification'
author: 'Bogdan Calapod <bogdan.calapod@codiantelligence.com>'
inputs:
  webhook:
    description: 'Teams Webhook to use'
    required: true
  title:
    description: 'The teams message title'
    required: false
    default: '💥 $GITHUB_REPOSITORY pipeline failed'
  body:
    description: 'Message body'
    required: false
    default: '* 📁 Repository: $GITHUB_REPOSITORY\n* 🌿 Branch: $GITHUB_REF_NAME'
  url:
    description: 'URL'
    required: false
    default: '$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID'
runs:
  using: 'composite'
  steps:
    - name: 💬 Teams notification
      shell: bash
      run: |
        cat << EOF > message.json
        {"@type":"MessageCard","@context":"http:\/\/schema.org\/extensions","themeColor":"0076D7","summary":"${{inputs.title}} ${{inputs.body}}","sections":[{"activityTitle":"${{inputs.title}}","activitySubtitle":"${{inputs.body}}","markdown":true}],"potentialAction":[{"@type":"OpenUri","name":"\ud83c\udf10 View on GitHub","targets":[{"os":"default","uri":"${{inputs.url}}"}]}]}
        EOF
        curl -X POST ${{ inputs.webhook }} --header 'Content-Type: application/json' -d @message.json
