name: '💬 Teams Notification'
description: 'Trigger a Microsoft Teams Notification'
author: 'Bogdan Calapod <bogdan.calapod@codiantelligence.com>'
inputs:
  webhook:
    description: 'Teams Webhook to use'
    required: true
  title:
    description: 'The teams message title'
    required: false
    default: '💥 $GITHUB_REPOSITORY pipeline failed'
runs:
  using: 'composite'
  steps:
    - name: 💬 Teams notification
      shell: bash
      run: |
        cat << EOF > message.json
        {"@type":"MessageCard","@context":"https://schema.org/extensions","summary":"${{inputs.title}}","themeColor":"ff0000","title":"${{ inputs.title }}","sections":[{"facts":[{"name":"Repository:","value":"$GITHUB_REPOSITORY"},{"name":"Branch:","value":"$GITHUB_REF_NAME"},{"name":"Commit:","value":"$GITHUB_SHA"}]}],"potentialAction":[{"@type":"OpenUri","name":"View on GitHub","targets":[{"os":"default","uri":"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"}]}]}
        EOF
        curl -X POST ${{ inputs.webhook }} --header 'Content-Type: application/json' -d @message.json
