name: '💬 Teams Notification'
description: 'Trigger a Microsoft Teams Notification'
author: 'Bogdan Calapod <bogdan.calapod@codiantelligence.com>'
inputs:
  webhook:
    description: 'Teams Webhook to use'
    required: true
  title:
    description: 'The teams message title'
    required: false
    default: '💥 $GITHUB_REPOSITORY pipeline failed'
  body:
    description: 'Message body'
    required: false
    default: '* 📁 Repository: $GITHUB_REPOSITORY\n* 🌿 Branch: $GITHUB_REF_NAME'
  url:
    description: 'URL'
    required: false
    default: '$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID'
runs:
  using: 'composite'
  steps:
    - name: 💬 Teams notification
      shell: bash
      run: |
        cat << EOF > message.json
        {"type":"message","attachments":[{"contentType":"application/vnd.microsoft.card.adaptive","contentUrl":null,"content":{"type":"AdaptiveCard","$schema":"http://adaptivecards.io/schemas/adaptive-card.json","version":"1.3","body":[{"type":"TextBlock","text":"${{inputs.title}}","wrap":true},{"type":"TextBlock","text":"${{inputs.body}}","wrap":true}],"actions":[{"type":"Action.OpenUrl","title":"🌐 View on GitHub","url":"${{inputs.url}}"}]}}]}
        EOF
        curl -X POST ${{ inputs.webhook }} --header 'Content-Type: application/json' -d @message.json
